name: standalone
on:
  workflow_dispatch:
    inputs:
      app:
        description: App to build (apps/<name>)
        required: true
        default: managed
      platform:
        description: Platform to build for (all/android/ios)
        required: true
        default: all
      profile:
        description: EAS build profile (development/production)
        required: true
        default: development
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }} # Required for apps/with-sentry
    steps:
      - name: 🚀 Setup repo
        uses: actions/checkout@v1
      - name: 🚀 Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: 🚀 Setup EAS
        uses: expo/expo-github-action@feature/expo-publish
        with:
          expo-version: latest
          expo-cache: true
          eas-version: latest
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - name: 🔎 Find cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: ♻️ Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 📋 Install dependencies
        run: yarn install --frozen-lockfile --check-files
      - name: 📱 Publish update
        uses: expo/expo-github-action/expo-publish@feature/expo-publish
        with:
          release-channel: test-gh-action
          working-directory: apps/${{ github.event.inputs.app }}
      - name: 📢 Start EAS build for ${{ github.event.inputs.app }}
        working-directory: apps/${{ github.event.inputs.app }}
        run: eas build --non-interactive --wait --platform=${{ github.event.inputs.platform }} --profile=${{ github.event.inputs.profile }}
