name: test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [16.x]
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: latest

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install --shamefully-hoist

      - name: 👷 Build packages
        run: pnpm run -r build

      - name: 🧪 Test packages
        run: pnpm run -r test
