name: test
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [14, 16]
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.17.2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install --shamefully-hoist
      - name: Build packages
        run: yarn build
      - name: Test packages
        run: yarn test
